---
output:
    html_document:
        toc: true
        toc_float:
            collapsed: false
        theme: lumen
        highlight: zenburn
        df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)
knitr::opts_chunk$set(include=TRUE)
knitr::opts_chunk$set(message=FALSE)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80), tidy=TRUE)
knitr::opts_knit$set(root.dir='.')
```

```{r library}
library(rstan)
library(rstanarm)
library(survey)
source("code/matching.R")
source("code/balance.R")
source("code/estimation.R")
library(cobalt)
library(rgenoud)
library(Matching)
library(CBPS)
library(WeightIt)
library(foreach)
```

```{r data}
load("data/cc2.Rdata")

covs_all <- setdiff(names(cc2), c("row.names", "row.names.1", "treat",
    "treat0", "ppvtr.36"))
covs <- c("bw", "preterm", "dayskidh", "sex", "first", "age", "black",
    "hispanic", "white", "b.marr", "lths", "hs", "ltcoll", "college",
    "work.dur", "prenatal", "momage")
cov_names <- c("birth weight", "weeks preterm", "days in hospital",
    "male", "first born", "age", "black", "hispanic", "white",
    "unmarried at birth", "less than high school", "high school graduate",
    "some college", "college graduate", "worked during pregnancy",
    "had no prenatal care", "age at birth")
```

Raw data balance
========================

```{r, include=TRUE}
ps_form <- formula(treat ~ bwg + hispanic + black + b.marr + lths + hs + ltcoll + work.dur + prenatal + sex + first + st5 + st9 + st12 + st25 + st36 + st42 + st48 + st53 + bw + preterm + momage + dayskidh)

bal.tab(ps_form, data=cc2, estimand='ATT', m.threshold=.1, v.threshold=1.1)
```

Propensity score models
==========================

```{r}
# Base logit model
{
    model <- 'models/ps_logit.rds'
    if (file.exists(model)){
        ps_logit <- readRDS(model)
    }  else{
        set.seed(20)
        ps_logit <- stan_glm(ps_form, family=binomial(link='logit'), data=cc2, algorithm='optimizing')
        saveRDS(ps_logit, model)
    }
    pscores_base <- apply(posterior_linpred(ps_logit, type='link'), 2, mean)
}

# CBPS
{
    model <- 'models/ps_cbps.rds'
    if (file.exists(model)){
        ps_cbps <- readRDS(model)
    } else{
        set.seed(20)
        ps_cbps <- CBPS(ps_form, data=cc2, ATT=1, method='over')
        saveRDS(ps_cbps, model)
    }
    pscores_cbps <-  ps_cbps$fitted.values
}

# Genetic matching
{
    model <- 'model/mgen_1.rds'
    if (file.exists(model)){
        set.seed(20)
        cl <- makePSOCKcluster(3)
        X <- setdiff(all.vars(ps_form), 'treeat')
        mgen_1 <- GenMatch(Tr=cc2$treat, X=cc2[,X], BalanceMatrix=cc2[,X], pop.size=1000, cluster=cl, balance=TRUE)
        saveRDS(mgen_1, model)
    } else{
        mgen_1 <- readRDS(model)
    }
}
```
