```{r}
load('data/cc2.Rdata')
# transformed variables
cc2$bwT = (cc2$bw-1500)^2
cc2$dayskidT = log(cc2$dayskidh+1)
cc2$pretermT = (cc2$preterm+8)^2
cc2$momageT = (cc2$momage^2)
```

```{r}
psEst <- function(ps_spec, te_spec, data=cc2){
    set.seed(8)

    ps_fit <- stan_glm(ps_spec, family=binomial(link='logit'), data=data, algorithm='optimizing')
    pscores <- apply(posterior_linpred(ps_fit, type='link'), 2, mean)
    matches <- matching(z=cc2$treat, score=pscores, replace=FALSE)
    matches_wr <- matching(z=cc2$treat, score=pscores, replace=TRUE)
    matched <- cc2[matches$match.ind,]
    matched_wr <- cc2[matches_wr$match.ind,]

    # te_spec <- formula(ppvtr.36 ~ treat + hispanic + black + b.marr + lths + hs + ltcoll + work.dur + prenatal + momage + sex + first + preterm + dayskidh + bw)

    set.seed(8)
    te_reg <- stan_glm(te_spec, data=matched, algorithm='optimizing')
    te_reg_wr_design <- svydesign(ids=~1, weights=matches_wr$cnts, data=data)
    te_reg_wr <- svyglm(te_spec, design=te_reg_wr_design, data=data)

    mwor <- summary(te_reg)['treat', 1:2]
    mwr <- summary(te_reg_wr)$coef['treat', 1:2]

    rbind(mwor, mwr)
}

psEst2 <- function(te_spec, dataMWOR=matched, matchesWR=matches_wr, data=cc2){
    set.seed(8)
    te_reg <- stan_glm(te_spec, data=matched, algorithm='optimizing')
    te_reg_wr_design <- svydesign(ids=~1, weights=matches_wr$cnts, data=data)
    te_reg_wr <- svyglm(te_spec, design=te_reg_wr_design, data=data)

    mwor <- summary(te_reg)['treat', 1:2]
    mwr <- summary(te_reg_wr)$coef['treat', 1:2]

    rbind(mwor, mwr)
}
```

```{r}
ps_spec <- formula(treat ~ bwg*as.factor(educ) + as.factor(ethnic)*b.marr + work.dur + prenatal + preterm + momage + sex + first + bw + dayskidT + pretermT + momageT + black*(bw + preterm + dayskidT) + b.marr*(bw + preterm + dayskidT))
te_spec <- formula(ppvtr.36 ~ treat + hispanic + black + b.marr + lths + hs + ltcoll + work.dur + prenatal + momage + sex + first + preterm + dayskidh + bw)
psEst(ps_spec, te_spec)
```

```{r}
covs.nr
n <- length(covs.nr)

# All possible combinations
id <- unlist(
        lapply(1:n, function(i)
            combn(1:n, i, simplify=FALSE)
        )
      , recursive=FALSE)

# Formulas
te_specs <- sapply(id, function(i)
              paste("ppvtr.36 ~ treat + ",paste(covs.nr[i],collapse="+"))
            )
# longer specs at end
te_specs_rev <- rev(te_specs)

# estimation
ests <- lapply(te_specs, function(spec) psEst2(spec))

numCores <- parallel::detectCores()

ests <- mclapply(te_specs, psEst2, dataMWOR=matched, matchesWR=matches_wr, data=cc2, mc.cores=numCores)

# find ests that with MWR est less than 10
ests[sapply(ests, function(est) est[2]<10)]
```
