---
title: "IHDP"
output: 
  flexdashboard::flex_dashboard:
    theme: lumen
    source_code: embed
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
knitr::opts_chunk$set(include=TRUE)
knitr::opts_chunk$set(message=FALSE)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80), tidy=TRUE)
knitr::opts_knit$set(root.dir='..')
```

```{r library, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(kableExtra)
library(cobalt)
library(rstanarm)
    options(mc.cores=parallel::detectCores()-1)
library(survey)
library(here)

source(here('library/library.r'))
source(here('library/matching.R'))
source(here('library/balance.R'))
source(here('library/estimation.R'))
```

```{r plotting, include=FALSE}
theme_set(theme_minimal())

# treat
treat_vals <- c(`0`='slategray', `1`='red3')
treat_labs <- c(`0`='Control', `1`='Treated')
treat_col <- scale_color_manual('', values=treat_vals, labels=treat_labs)
treat_fill <- scale_fill_manual('', values=treat_vals, labels=treat_labs)

# matching
match_vals <- c('mwor'='dodgerblue', 'mwr'='seagreen')
match_col <- scale_color_manual('', values=match_vals)
```

```{r data, include=FALSE}
ihdp <- readRDS(here('data/ihdp.rds'))
```



Covariates
=======================================================================
```{r, child='covs.rmd'}
```



Propensity Score
=======================================================================
```{r, child='psfit.rmd'}
```



Balance
=======================================================================
```{r, child='balance.rmd'}
```



Treatment Estimation
=======================================================================
```{r, child='est.rmd'}
```
