---
title: IHDP analyses for CH10 of GH
output: pdf_document
---

```{r rmd_setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
knitr::opts_chunk$set(include=TRUE)
knitr::opts_chunk$set(message=FALSE)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80), tidy=TRUE)
knitr::opts_knit$set(root.dir='..')
```

```{r libraries, include=FALSE}

```

# Data prep

```{r data prep}
cc <- read.table("data/ihdp.nlsy.imp1.txt",header=T,sep="\t")
cc$treat <- cc$treat-1

cc$ethnic = cc$hispanic
cc$ethnic[cc$black==1]=2
cc$ethnic[cc$white==1]=3

cc$educ = cc$lths
cc$educ[cc$hs==1]=2
cc$educ[cc$ltcoll==1]=3
cc$educ[cc$college==1]=4
cc$educ3=cc$educ
cc$educ3[cc$educ>2]=cc$educ3[cc$educ>2]-1

cc$bwg=(cc$bw>2000)*1

cc$state=cc$st5
cc$state[cc$st9==1]=2
cc$state[cc$st12==1]=3
cc$state[cc$st25==1]=4
cc$state[cc$st36==1]=5
cc$state[cc$st42==1]=6
cc$state[cc$st48==1]=7
cc$state[cc$st53==1]=8

cc$state2=cc$state
cc$state2[cc$st5==1]=0

cc$state3=cc$state
cc$state3[cc$st53==1]=0

cc2<-cc[cc$bw>1500,]

cc2$neg.bw = 2500 - cc2$bw
cc2$no.prenatal = 1-cc2$prenatal
cc2$b.unmarr = 1-cc2$b.marr

covs <- c("hispanic","black","white","b.marr","lths","hs","ltcoll","college","work.dur","prenatal","momage","sex","first","preterm","age","dayskidh","bw")
covs.st <- c("hispanic","black","white","b.marr","lths","hs","ltcoll","college","work.dur","prenatal","momage","sex","first","age","preterm","dayskidh","bw","unemp.rt","st5","st9","st12","st25","st36","st42","st48","st53")

covs.nba <- c("hispanic","black","white","b.marr","lths","hs","ltcoll","college",
             "work.dur","prenatal","momage","sex","first","age")
covs.ba <- c("dayskidh","bw","preterm")

cc2$bwT = (cc2$bw-1500)^2
#cc2$bwT = (cc2$neg.bw+5100)^2
cc2$dayskidT = log(cc2$dayskidh+1)
cc2$pretermT = (cc2$preterm+8)^2
cc2$momageT = (cc2$momage^2)

############################################
## make a dataset to investigate bias amplification
data.ba = cc2[,c("ppvtr.36", "treat", covs.ba,covs.nba)]
lm(data.ba)

data.nba = cc2[,c("ppvtr.36", "treat",covs.nba)]
lm(data.nba)
```

# Univariate

```{r}
hist(cc2$bw[cc2$treat==1], xlim=c(0,6000), main="treatment group", xlab="birthweight", freq=F)
hist(cc2$bw[cc2$treat==0], xlim=c(0,6000), main="control group", xlab="birthweight", freq=F, add=T, border="darkgrey")

hist(cc2$bw[cc2$treat==0], xlim=c(0,6000), main="control group", xlab="birthweight", border="darkgrey")
hist(cc2$bw[cc2$treat==1], xlim=c(0,6000), main="treatment group", xlab="birthweight", add=T)

# breaks the same across groups
hist(cc2$bw[cc2$treat==0], xlim=c(0,6000), main="control group", xlab="birthweight", border="darkgrey", breaks=seq(0,6000,400))
hist(cc2$bw[cc2$treat==1], xlim=c(0,6000), main="treatment group", xlab="birthweight", add=T, breaks=seq(0,6000,400))

hist(cc2$age[cc2$treat==1], xlim=c(0,110), main="treatment group", xlab="age", breaks=seq(0,110,10), freq=F)
hist(cc2$age[cc2$treat==0], xlim=c(0,110), main="control group", xlab="age", border="darkgrey", add=T, breaks=seq(0,110,10), freq=F)

## now preterm
hist(cc2$preterm[cc2$treat==0], xlim=c(0,6000), main="control group",xlab="birthweight", border="darkgrey")
hist(cc2$preterm[cc2$treat==1], xlim=c(0,6000), main="treatment group",xlab="birthweight", add=T)

## now educ
hist(cc$educ[cc$treat==0], xlim=c(0,5), main="control group", xlab="education", border="darkgrey", freq=F)
hist(cc$educ[cc$treat==1], xlim=c(0,5), main="treatment group", xlab="education", add=T, freq=F)

hist(cc$college[cc$treat==0], xlim=c(0,5), main="control group", xlab="college", border="darkgrey", freq=F)
hist(cc$college[cc$treat==1], xlim=c(0,5), main="treatment group", xlab="college", add=T, freq=F)

hist(cc$educ3[cc$treat==0], xlim=c(0,5), main="control group", xlab="educ3", border="darkgrey", freq=F)
hist(cc$educ3[cc$treat==1], xlim=c(0,5), main="treatment group",  xlab="educ3", add=T, freq=F)

## plots actually used to illustrate distinctions between overlap and balance
# now age
plot(x=seq(0,5,.1), y=seq(0,1800,(1800/50)), bty="n", xaxt="n", yaxt="n", mgp=c(2,.5,0), xlab="mother's education", ylab="frequency", type="n", main="")
axis(1, 1:4)
axis(2, c(0,1000,2000))
hist(cc2$educ[cc$treat==0], xlim=c(0,5), main="", border="darkgrey", breaks=c(.5,1.5,2.5,3.5,4.5), add=T)
hist(cc2$educ[cc$treat==1], xlim=c(0,5), xlab="education", breaks=c(.5,1.5,2.5,3.5,4.5), add=T)

hist(cc2$age[cc2$treat==0], xlim=c(0,110), main="", xlab="age of child (months)", border="darkgrey", breaks=seq(0,110,10), mgp=c(2,.5,0))
hist(cc2$age[cc2$treat==1], xlim=c(0,110), xlab="", breaks=seq(0,110,10), add=T)
```
